"""upgreade tables with news methods especificly mapped

Revision ID: b596510b37de
Revises: 10e9cfc681a7
Create Date: 2026-07-27 08:28:47.308216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b596510b37de'
down_revision: Union[str, Sequence[str], None] = '10e9cfc681a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
