"""coloquei slug na minha tabela

Revision ID: c34f40605c49
Revises: d96ef4784197
Create Date: 2026-07-28 17:14:22.823694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34f40605c49'
down_revision: Union[str, Sequence[str], None] = 'd96ef4784197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automation', sa.Column('slug', sa.String(length=30), nullable=False))
    op.create_unique_constraint(None, 'automation', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'automation', type_='unique')
    op.drop_column('automation', 'slug')
    # ### end Alembic commands ###
