"""adiciona error_message em executions e steps

Revision ID: d96ef4784197
Revises: b596510b37de
Create Date: 2026-07-27 17:38:09.329653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96ef4784197'
down_revision: Union[str, Sequence[str], None] = 'b596510b37de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('steps', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'error_message')
    op.drop_column('executions', 'error_message')
    # ### end Alembic commands ###
