services:
  automations-hub:
    build:
      context: .
      dockerfile: apps/automations-hub/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    volumes:
      - ./apps/automations-hub:/app/apps/automations-hub
      - ./packages/shared:/app/packages/shared
    restart: unless-stopped

  ui:
    build:
      context: ./apps/ui-client
      dockerfile: Dockerfile
      args:
        AUTOMATION_HUB: ${AUTOMATION_HUB}
    ports:
      - "5173:3000"
    env_file:
      - .env.production
    depends_on:
      - automations-hub
    restart: unless-stopped
