/**
 * Generated by orval 🍺
 * Do not edit manually.
 * automations-hub
 *
 *     O `orchestrator-api` é o **control plane** do `organize-tasks`: o serviço que sabe
 *     quais automações existem, qual o status de cada uma, o histórico de execuções,
 *     e consegue pausar/reativar cada uma — sem precisar entrar em cada automação
 *     individualmente pra saber o que está acontecendo.
 *
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { api } from './axios';
export interface AutomationResponse {
  id: number;
  slug: string;
  name: string;
  description: string | null;
  trigger: string;
  status: string;
}

export interface AutomationStatsResponse {
  success_rate: number;
  average_duration: number;
  total_executions: number;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface MetricResponse {
  id: number;
  execution_at: string;
  name: string;
  value: number;
  step_id: number;
}

export interface PauseAutomationResponse {
  message: string;
}

export interface TriggerAutomationResponse {
  message: string;
}

export interface AutomationsHubDtoAutomationDtoExecutionResponse {
  id: number;
  status: string;
  start_at: string;
  end_at: string | null;
  error_message: string | null;
}

export interface AutomationsHubDtoExecutionDtoStepResponse {
  id: number;
  name: string;
  status: string;
  error_message: string | null;
}

export interface AutomationsHubDtoExecutionDtoExecutionResponse {
  id: number;
  automation_id: number;
  status: string;
  start_at: string;
  end_at: string | null;
  error_message: string | null;
  steps: AutomationsHubDtoExecutionDtoStepResponse[];
}

export interface AutomationsHubDtoStepsStepResponse {
  id: number;
  execution_id: number;
  name: string;
  status: string;
  error_message?: string | null;
}

export type RootGet200 = { [key: string]: unknown };

export type HealthHealthGet200 = { [key: string]: unknown };

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listAutomationsApi010AutomationsGetResponse200 = {
  data: AutomationResponse[]
  status: 200
}

export type listAutomationsApi010AutomationsGetResponseSuccess = (listAutomationsApi010AutomationsGetResponse200) & {
  headers: Headers;
};
;

export type listAutomationsApi010AutomationsGetResponse = (listAutomationsApi010AutomationsGetResponseSuccess)

export const getListAutomationsApi010AutomationsGetUrl = () => {




  return `/api/0.1.0/automations/`
}

/**
 * Lista todas as automações.
 * @summary List Automations
 */
export const listAutomationsApi010AutomationsGet = async ( options?: Parameters<typeof api>[1]): Promise<listAutomationsApi010AutomationsGetResponse> => {

  return api<listAutomationsApi010AutomationsGetResponse>(getListAutomationsApi010AutomationsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAutomationsApi010AutomationsGetQueryKey = () => {
    return [
    `/api/0.1.0/automations/`
    ] as const;
    }


export const getListAutomationsApi010AutomationsGetQueryOptions = <TData = Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAutomationsApi010AutomationsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>> = ({ signal }) => listAutomationsApi010AutomationsGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAutomationsApi010AutomationsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>>
export type ListAutomationsApi010AutomationsGetQueryError = unknown


export function useListAutomationsApi010AutomationsGet<TData = Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>,
          TError,
          Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAutomationsApi010AutomationsGet<TData = Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>,
          TError,
          Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAutomationsApi010AutomationsGet<TData = Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Automations
 */

export function useListAutomationsApi010AutomationsGet<TData = Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomationsApi010AutomationsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAutomationsApi010AutomationsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getAutomationDetailApi010AutomationsSlugGetResponse200 = {
  data: AutomationResponse
  status: 200
}

export type getAutomationDetailApi010AutomationsSlugGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getAutomationDetailApi010AutomationsSlugGetResponseSuccess = (getAutomationDetailApi010AutomationsSlugGetResponse200) & {
  headers: Headers;
};
export type getAutomationDetailApi010AutomationsSlugGetResponseError = (getAutomationDetailApi010AutomationsSlugGetResponse422) & {
  headers: Headers;
};

export type getAutomationDetailApi010AutomationsSlugGetResponse = (getAutomationDetailApi010AutomationsSlugGetResponseSuccess | getAutomationDetailApi010AutomationsSlugGetResponseError)

export const getGetAutomationDetailApi010AutomationsSlugGetUrl = (slug: string,) => {




  return `/api/0.1.0/automations/${slug}`
}

/**
 * Detalhe de uma automação pelo slug.
 * @summary Get Automation Detail
 */
export const getAutomationDetailApi010AutomationsSlugGet = async (slug: string, options?: Parameters<typeof api>[1]): Promise<getAutomationDetailApi010AutomationsSlugGetResponse> => {

  return api<getAutomationDetailApi010AutomationsSlugGetResponse>(getGetAutomationDetailApi010AutomationsSlugGetUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAutomationDetailApi010AutomationsSlugGetQueryKey = (slug: string,) => {
    return [
    `/api/0.1.0/automations/${slug}`
    ] as const;
    }


export const getGetAutomationDetailApi010AutomationsSlugGetQueryOptions = <TData = Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>, TError = HTTPValidationError>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAutomationDetailApi010AutomationsSlugGetQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>> = ({ signal }) => getAutomationDetailApi010AutomationsSlugGet(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAutomationDetailApi010AutomationsSlugGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>>
export type GetAutomationDetailApi010AutomationsSlugGetQueryError = HTTPValidationError


export function useGetAutomationDetailApi010AutomationsSlugGet<TData = Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>, TError = HTTPValidationError>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>,
          TError,
          Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAutomationDetailApi010AutomationsSlugGet<TData = Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>,
          TError,
          Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAutomationDetailApi010AutomationsSlugGet<TData = Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Automation Detail
 */

export function useGetAutomationDetailApi010AutomationsSlugGet<TData = Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationDetailApi010AutomationsSlugGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAutomationDetailApi010AutomationsSlugGetQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type pauseAutomationApi010AutomationsSlugPausePatchResponse200 = {
  data: PauseAutomationResponse
  status: 200
}

export type pauseAutomationApi010AutomationsSlugPausePatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type pauseAutomationApi010AutomationsSlugPausePatchResponseSuccess = (pauseAutomationApi010AutomationsSlugPausePatchResponse200) & {
  headers: Headers;
};
export type pauseAutomationApi010AutomationsSlugPausePatchResponseError = (pauseAutomationApi010AutomationsSlugPausePatchResponse422) & {
  headers: Headers;
};

export type pauseAutomationApi010AutomationsSlugPausePatchResponse = (pauseAutomationApi010AutomationsSlugPausePatchResponseSuccess | pauseAutomationApi010AutomationsSlugPausePatchResponseError)

export const getPauseAutomationApi010AutomationsSlugPausePatchUrl = (slug: string,) => {




  return `/api/0.1.0/automations/${slug}/pause`
}

/**
 * Pausa uma automação.
 * @summary Pause Automation
 */
export const pauseAutomationApi010AutomationsSlugPausePatch = async (slug: string, options?: Parameters<typeof api>[1]): Promise<pauseAutomationApi010AutomationsSlugPausePatchResponse> => {

  return api<pauseAutomationApi010AutomationsSlugPausePatchResponse>(getPauseAutomationApi010AutomationsSlugPausePatchUrl(slug),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getPauseAutomationApi010AutomationsSlugPausePatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pauseAutomationApi010AutomationsSlugPausePatch>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof pauseAutomationApi010AutomationsSlugPausePatch>>, TError,{slug: string}, TContext> => {

const mutationKey = ['pauseAutomationApi010AutomationsSlugPausePatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pauseAutomationApi010AutomationsSlugPausePatch>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  pauseAutomationApi010AutomationsSlugPausePatch(slug,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PauseAutomationApi010AutomationsSlugPausePatchMutationResult = NonNullable<Awaited<ReturnType<typeof pauseAutomationApi010AutomationsSlugPausePatch>>>

    export type PauseAutomationApi010AutomationsSlugPausePatchMutationError = HTTPValidationError

    /**
 * @summary Pause Automation
 */
export const usePauseAutomationApi010AutomationsSlugPausePatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pauseAutomationApi010AutomationsSlugPausePatch>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pauseAutomationApi010AutomationsSlugPausePatch>>,
        TError,
        {slug: string},
        TContext
      > => {
      return useMutation(getPauseAutomationApi010AutomationsSlugPausePatchMutationOptions(options), queryClient);
    }

export type resumeAutomationApi010AutomationsSlugResumePatchResponse200 = {
  data: PauseAutomationResponse
  status: 200
}

export type resumeAutomationApi010AutomationsSlugResumePatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type resumeAutomationApi010AutomationsSlugResumePatchResponseSuccess = (resumeAutomationApi010AutomationsSlugResumePatchResponse200) & {
  headers: Headers;
};
export type resumeAutomationApi010AutomationsSlugResumePatchResponseError = (resumeAutomationApi010AutomationsSlugResumePatchResponse422) & {
  headers: Headers;
};

export type resumeAutomationApi010AutomationsSlugResumePatchResponse = (resumeAutomationApi010AutomationsSlugResumePatchResponseSuccess | resumeAutomationApi010AutomationsSlugResumePatchResponseError)

export const getResumeAutomationApi010AutomationsSlugResumePatchUrl = (slug: string,) => {




  return `/api/0.1.0/automations/${slug}/resume`
}

/**
 * Retoma uma automação.
 * @summary Resume Automation
 */
export const resumeAutomationApi010AutomationsSlugResumePatch = async (slug: string, options?: Parameters<typeof api>[1]): Promise<resumeAutomationApi010AutomationsSlugResumePatchResponse> => {

  return api<resumeAutomationApi010AutomationsSlugResumePatchResponse>(getResumeAutomationApi010AutomationsSlugResumePatchUrl(slug),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getResumeAutomationApi010AutomationsSlugResumePatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resumeAutomationApi010AutomationsSlugResumePatch>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof resumeAutomationApi010AutomationsSlugResumePatch>>, TError,{slug: string}, TContext> => {

const mutationKey = ['resumeAutomationApi010AutomationsSlugResumePatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resumeAutomationApi010AutomationsSlugResumePatch>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  resumeAutomationApi010AutomationsSlugResumePatch(slug,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResumeAutomationApi010AutomationsSlugResumePatchMutationResult = NonNullable<Awaited<ReturnType<typeof resumeAutomationApi010AutomationsSlugResumePatch>>>

    export type ResumeAutomationApi010AutomationsSlugResumePatchMutationError = HTTPValidationError

    /**
 * @summary Resume Automation
 */
export const useResumeAutomationApi010AutomationsSlugResumePatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resumeAutomationApi010AutomationsSlugResumePatch>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resumeAutomationApi010AutomationsSlugResumePatch>>,
        TError,
        {slug: string},
        TContext
      > => {
      return useMutation(getResumeAutomationApi010AutomationsSlugResumePatchMutationOptions(options), queryClient);
    }

export type triggerAutomationApi010AutomationsSlugTriggerPostResponse200 = {
  data: TriggerAutomationResponse
  status: 200
}

export type triggerAutomationApi010AutomationsSlugTriggerPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type triggerAutomationApi010AutomationsSlugTriggerPostResponseSuccess = (triggerAutomationApi010AutomationsSlugTriggerPostResponse200) & {
  headers: Headers;
};
export type triggerAutomationApi010AutomationsSlugTriggerPostResponseError = (triggerAutomationApi010AutomationsSlugTriggerPostResponse422) & {
  headers: Headers;
};

export type triggerAutomationApi010AutomationsSlugTriggerPostResponse = (triggerAutomationApi010AutomationsSlugTriggerPostResponseSuccess | triggerAutomationApi010AutomationsSlugTriggerPostResponseError)

export const getTriggerAutomationApi010AutomationsSlugTriggerPostUrl = (slug: string,) => {




  return `/api/0.1.0/automations/${slug}/trigger`
}

/**
 * Dispara execução manual de uma automação.
 * @summary Trigger Automation
 */
export const triggerAutomationApi010AutomationsSlugTriggerPost = async (slug: string, options?: Parameters<typeof api>[1]): Promise<triggerAutomationApi010AutomationsSlugTriggerPostResponse> => {

  return api<triggerAutomationApi010AutomationsSlugTriggerPostResponse>(getTriggerAutomationApi010AutomationsSlugTriggerPostUrl(slug),
  {
    ...options,
    method: 'POST'


  }
);}





export const getTriggerAutomationApi010AutomationsSlugTriggerPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerAutomationApi010AutomationsSlugTriggerPost>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof triggerAutomationApi010AutomationsSlugTriggerPost>>, TError,{slug: string}, TContext> => {

const mutationKey = ['triggerAutomationApi010AutomationsSlugTriggerPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerAutomationApi010AutomationsSlugTriggerPost>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  triggerAutomationApi010AutomationsSlugTriggerPost(slug,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TriggerAutomationApi010AutomationsSlugTriggerPostMutationResult = NonNullable<Awaited<ReturnType<typeof triggerAutomationApi010AutomationsSlugTriggerPost>>>

    export type TriggerAutomationApi010AutomationsSlugTriggerPostMutationError = HTTPValidationError

    /**
 * @summary Trigger Automation
 */
export const useTriggerAutomationApi010AutomationsSlugTriggerPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerAutomationApi010AutomationsSlugTriggerPost>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof triggerAutomationApi010AutomationsSlugTriggerPost>>,
        TError,
        {slug: string},
        TContext
      > => {
      return useMutation(getTriggerAutomationApi010AutomationsSlugTriggerPostMutationOptions(options), queryClient);
    }

export type listAutomationExecutionsApi010AutomationsSlugExecutionsGetResponse200 = {
  data: AutomationsHubDtoAutomationDtoExecutionResponse[]
  status: 200
}

export type listAutomationExecutionsApi010AutomationsSlugExecutionsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listAutomationExecutionsApi010AutomationsSlugExecutionsGetResponseSuccess = (listAutomationExecutionsApi010AutomationsSlugExecutionsGetResponse200) & {
  headers: Headers;
};
export type listAutomationExecutionsApi010AutomationsSlugExecutionsGetResponseError = (listAutomationExecutionsApi010AutomationsSlugExecutionsGetResponse422) & {
  headers: Headers;
};

export type listAutomationExecutionsApi010AutomationsSlugExecutionsGetResponse = (listAutomationExecutionsApi010AutomationsSlugExecutionsGetResponseSuccess | listAutomationExecutionsApi010AutomationsSlugExecutionsGetResponseError)

export const getListAutomationExecutionsApi010AutomationsSlugExecutionsGetUrl = (slug: string,) => {




  return `/api/0.1.0/automations/${slug}/executions`
}

/**
 * Histórico de execuções dessa automação.
 * @summary List Automation Executions
 */
export const listAutomationExecutionsApi010AutomationsSlugExecutionsGet = async (slug: string, options?: Parameters<typeof api>[1]): Promise<listAutomationExecutionsApi010AutomationsSlugExecutionsGetResponse> => {

  return api<listAutomationExecutionsApi010AutomationsSlugExecutionsGetResponse>(getListAutomationExecutionsApi010AutomationsSlugExecutionsGetUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAutomationExecutionsApi010AutomationsSlugExecutionsGetQueryKey = (slug: string,) => {
    return [
    `/api/0.1.0/automations/${slug}/executions`
    ] as const;
    }


export const getListAutomationExecutionsApi010AutomationsSlugExecutionsGetQueryOptions = <TData = Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>, TError = HTTPValidationError>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAutomationExecutionsApi010AutomationsSlugExecutionsGetQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>> = ({ signal }) => listAutomationExecutionsApi010AutomationsSlugExecutionsGet(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAutomationExecutionsApi010AutomationsSlugExecutionsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>>
export type ListAutomationExecutionsApi010AutomationsSlugExecutionsGetQueryError = HTTPValidationError


export function useListAutomationExecutionsApi010AutomationsSlugExecutionsGet<TData = Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>, TError = HTTPValidationError>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>,
          TError,
          Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAutomationExecutionsApi010AutomationsSlugExecutionsGet<TData = Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>,
          TError,
          Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAutomationExecutionsApi010AutomationsSlugExecutionsGet<TData = Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Automation Executions
 */

export function useListAutomationExecutionsApi010AutomationsSlugExecutionsGet<TData = Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomationExecutionsApi010AutomationsSlugExecutionsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAutomationExecutionsApi010AutomationsSlugExecutionsGetQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getAutomationStatsApi010AutomationsSlugStatsGetResponse200 = {
  data: AutomationStatsResponse
  status: 200
}

export type getAutomationStatsApi010AutomationsSlugStatsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getAutomationStatsApi010AutomationsSlugStatsGetResponseSuccess = (getAutomationStatsApi010AutomationsSlugStatsGetResponse200) & {
  headers: Headers;
};
export type getAutomationStatsApi010AutomationsSlugStatsGetResponseError = (getAutomationStatsApi010AutomationsSlugStatsGetResponse422) & {
  headers: Headers;
};

export type getAutomationStatsApi010AutomationsSlugStatsGetResponse = (getAutomationStatsApi010AutomationsSlugStatsGetResponseSuccess | getAutomationStatsApi010AutomationsSlugStatsGetResponseError)

export const getGetAutomationStatsApi010AutomationsSlugStatsGetUrl = (slug: string,) => {




  return `/api/0.1.0/automations/${slug}/stats`
}

/**
 * Taxa de sucesso e duração média da automação.
 * @summary Get Automation Stats
 */
export const getAutomationStatsApi010AutomationsSlugStatsGet = async (slug: string, options?: Parameters<typeof api>[1]): Promise<getAutomationStatsApi010AutomationsSlugStatsGetResponse> => {

  return api<getAutomationStatsApi010AutomationsSlugStatsGetResponse>(getGetAutomationStatsApi010AutomationsSlugStatsGetUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAutomationStatsApi010AutomationsSlugStatsGetQueryKey = (slug: string,) => {
    return [
    `/api/0.1.0/automations/${slug}/stats`
    ] as const;
    }


export const getGetAutomationStatsApi010AutomationsSlugStatsGetQueryOptions = <TData = Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>, TError = HTTPValidationError>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAutomationStatsApi010AutomationsSlugStatsGetQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>> = ({ signal }) => getAutomationStatsApi010AutomationsSlugStatsGet(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAutomationStatsApi010AutomationsSlugStatsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>>
export type GetAutomationStatsApi010AutomationsSlugStatsGetQueryError = HTTPValidationError


export function useGetAutomationStatsApi010AutomationsSlugStatsGet<TData = Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>, TError = HTTPValidationError>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>,
          TError,
          Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAutomationStatsApi010AutomationsSlugStatsGet<TData = Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>,
          TError,
          Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAutomationStatsApi010AutomationsSlugStatsGet<TData = Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Automation Stats
 */

export function useGetAutomationStatsApi010AutomationsSlugStatsGet<TData = Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationStatsApi010AutomationsSlugStatsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAutomationStatsApi010AutomationsSlugStatsGetQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getExecutionDetailApi010ExecutionsExecutionIdGetResponse200 = {
  data: AutomationsHubDtoExecutionDtoExecutionResponse
  status: 200
}

export type getExecutionDetailApi010ExecutionsExecutionIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getExecutionDetailApi010ExecutionsExecutionIdGetResponseSuccess = (getExecutionDetailApi010ExecutionsExecutionIdGetResponse200) & {
  headers: Headers;
};
export type getExecutionDetailApi010ExecutionsExecutionIdGetResponseError = (getExecutionDetailApi010ExecutionsExecutionIdGetResponse422) & {
  headers: Headers;
};

export type getExecutionDetailApi010ExecutionsExecutionIdGetResponse = (getExecutionDetailApi010ExecutionsExecutionIdGetResponseSuccess | getExecutionDetailApi010ExecutionsExecutionIdGetResponseError)

export const getGetExecutionDetailApi010ExecutionsExecutionIdGetUrl = (executionId: number,) => {




  return `/api/0.1.0/executions/${executionId}`
}

/**
 * Detalhe de uma execução (com steps).
 * @summary Get Execution Detail
 */
export const getExecutionDetailApi010ExecutionsExecutionIdGet = async (executionId: number, options?: Parameters<typeof api>[1]): Promise<getExecutionDetailApi010ExecutionsExecutionIdGetResponse> => {

  return api<getExecutionDetailApi010ExecutionsExecutionIdGetResponse>(getGetExecutionDetailApi010ExecutionsExecutionIdGetUrl(executionId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetExecutionDetailApi010ExecutionsExecutionIdGetQueryKey = (executionId: number,) => {
    return [
    `/api/0.1.0/executions/${executionId}`
    ] as const;
    }


export const getGetExecutionDetailApi010ExecutionsExecutionIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>, TError = HTTPValidationError>(executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetExecutionDetailApi010ExecutionsExecutionIdGetQueryKey(executionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>> = ({ signal }) => getExecutionDetailApi010ExecutionsExecutionIdGet(executionId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: executionId !== null && executionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetExecutionDetailApi010ExecutionsExecutionIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>>
export type GetExecutionDetailApi010ExecutionsExecutionIdGetQueryError = HTTPValidationError


export function useGetExecutionDetailApi010ExecutionsExecutionIdGet<TData = Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>, TError = HTTPValidationError>(
 executionId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>,
          TError,
          Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExecutionDetailApi010ExecutionsExecutionIdGet<TData = Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>,
          TError,
          Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExecutionDetailApi010ExecutionsExecutionIdGet<TData = Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Execution Detail
 */

export function useGetExecutionDetailApi010ExecutionsExecutionIdGet<TData = Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionDetailApi010ExecutionsExecutionIdGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetExecutionDetailApi010ExecutionsExecutionIdGetQueryOptions(executionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getExecutionStepsApi010ExecutionsExecutionIdStepsGetResponse200 = {
  data: AutomationsHubDtoExecutionDtoStepResponse[]
  status: 200
}

export type getExecutionStepsApi010ExecutionsExecutionIdStepsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getExecutionStepsApi010ExecutionsExecutionIdStepsGetResponseSuccess = (getExecutionStepsApi010ExecutionsExecutionIdStepsGetResponse200) & {
  headers: Headers;
};
export type getExecutionStepsApi010ExecutionsExecutionIdStepsGetResponseError = (getExecutionStepsApi010ExecutionsExecutionIdStepsGetResponse422) & {
  headers: Headers;
};

export type getExecutionStepsApi010ExecutionsExecutionIdStepsGetResponse = (getExecutionStepsApi010ExecutionsExecutionIdStepsGetResponseSuccess | getExecutionStepsApi010ExecutionsExecutionIdStepsGetResponseError)

export const getGetExecutionStepsApi010ExecutionsExecutionIdStepsGetUrl = (executionId: number,) => {




  return `/api/0.1.0/executions/${executionId}/steps`
}

/**
 * Só os steps dessa execução.
 * @summary Get Execution Steps
 */
export const getExecutionStepsApi010ExecutionsExecutionIdStepsGet = async (executionId: number, options?: Parameters<typeof api>[1]): Promise<getExecutionStepsApi010ExecutionsExecutionIdStepsGetResponse> => {

  return api<getExecutionStepsApi010ExecutionsExecutionIdStepsGetResponse>(getGetExecutionStepsApi010ExecutionsExecutionIdStepsGetUrl(executionId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetExecutionStepsApi010ExecutionsExecutionIdStepsGetQueryKey = (executionId: number,) => {
    return [
    `/api/0.1.0/executions/${executionId}/steps`
    ] as const;
    }


export const getGetExecutionStepsApi010ExecutionsExecutionIdStepsGetQueryOptions = <TData = Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>, TError = HTTPValidationError>(executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetExecutionStepsApi010ExecutionsExecutionIdStepsGetQueryKey(executionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>> = ({ signal }) => getExecutionStepsApi010ExecutionsExecutionIdStepsGet(executionId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: executionId !== null && executionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetExecutionStepsApi010ExecutionsExecutionIdStepsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>>
export type GetExecutionStepsApi010ExecutionsExecutionIdStepsGetQueryError = HTTPValidationError


export function useGetExecutionStepsApi010ExecutionsExecutionIdStepsGet<TData = Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>, TError = HTTPValidationError>(
 executionId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>,
          TError,
          Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExecutionStepsApi010ExecutionsExecutionIdStepsGet<TData = Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>,
          TError,
          Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExecutionStepsApi010ExecutionsExecutionIdStepsGet<TData = Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Execution Steps
 */

export function useGetExecutionStepsApi010ExecutionsExecutionIdStepsGet<TData = Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionStepsApi010ExecutionsExecutionIdStepsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetExecutionStepsApi010ExecutionsExecutionIdStepsGetQueryOptions(executionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type listStepMetricsApi010ExecutionsStepsStepIdMetricsGetResponse200 = {
  data: MetricResponse[]
  status: 200
}

export type listStepMetricsApi010ExecutionsStepsStepIdMetricsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listStepMetricsApi010ExecutionsStepsStepIdMetricsGetResponseSuccess = (listStepMetricsApi010ExecutionsStepsStepIdMetricsGetResponse200) & {
  headers: Headers;
};
export type listStepMetricsApi010ExecutionsStepsStepIdMetricsGetResponseError = (listStepMetricsApi010ExecutionsStepsStepIdMetricsGetResponse422) & {
  headers: Headers;
};

export type listStepMetricsApi010ExecutionsStepsStepIdMetricsGetResponse = (listStepMetricsApi010ExecutionsStepsStepIdMetricsGetResponseSuccess | listStepMetricsApi010ExecutionsStepsStepIdMetricsGetResponseError)

export const getListStepMetricsApi010ExecutionsStepsStepIdMetricsGetUrl = (stepId: number,) => {




  return `/api/0.1.0/executions/steps/${stepId}/metrics`
}

/**
 * Lista as métricas de um step.
 * @summary List Step Metrics
 */
export const listStepMetricsApi010ExecutionsStepsStepIdMetricsGet = async (stepId: number, options?: Parameters<typeof api>[1]): Promise<listStepMetricsApi010ExecutionsStepsStepIdMetricsGetResponse> => {

  return api<listStepMetricsApi010ExecutionsStepsStepIdMetricsGetResponse>(getListStepMetricsApi010ExecutionsStepsStepIdMetricsGetUrl(stepId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListStepMetricsApi010ExecutionsStepsStepIdMetricsGetQueryKey = (stepId: number,) => {
    return [
    `/api/0.1.0/executions/steps/${stepId}/metrics`
    ] as const;
    }


export const getListStepMetricsApi010ExecutionsStepsStepIdMetricsGetQueryOptions = <TData = Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>, TError = HTTPValidationError>(stepId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStepMetricsApi010ExecutionsStepsStepIdMetricsGetQueryKey(stepId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>> = ({ signal }) => listStepMetricsApi010ExecutionsStepsStepIdMetricsGet(stepId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: stepId !== null && stepId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStepMetricsApi010ExecutionsStepsStepIdMetricsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>>
export type ListStepMetricsApi010ExecutionsStepsStepIdMetricsGetQueryError = HTTPValidationError


export function useListStepMetricsApi010ExecutionsStepsStepIdMetricsGet<TData = Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>, TError = HTTPValidationError>(
 stepId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>,
          TError,
          Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStepMetricsApi010ExecutionsStepsStepIdMetricsGet<TData = Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>, TError = HTTPValidationError>(
 stepId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>,
          TError,
          Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStepMetricsApi010ExecutionsStepsStepIdMetricsGet<TData = Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>, TError = HTTPValidationError>(
 stepId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Step Metrics
 */

export function useListStepMetricsApi010ExecutionsStepsStepIdMetricsGet<TData = Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>, TError = HTTPValidationError>(
 stepId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStepMetricsApi010ExecutionsStepsStepIdMetricsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStepMetricsApi010ExecutionsStepsStepIdMetricsGetQueryOptions(stepId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getMetricApi010ExecutionsMetricsMetricIdGetResponse200 = {
  data: MetricResponse
  status: 200
}

export type getMetricApi010ExecutionsMetricsMetricIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getMetricApi010ExecutionsMetricsMetricIdGetResponseSuccess = (getMetricApi010ExecutionsMetricsMetricIdGetResponse200) & {
  headers: Headers;
};
export type getMetricApi010ExecutionsMetricsMetricIdGetResponseError = (getMetricApi010ExecutionsMetricsMetricIdGetResponse422) & {
  headers: Headers;
};

export type getMetricApi010ExecutionsMetricsMetricIdGetResponse = (getMetricApi010ExecutionsMetricsMetricIdGetResponseSuccess | getMetricApi010ExecutionsMetricsMetricIdGetResponseError)

export const getGetMetricApi010ExecutionsMetricsMetricIdGetUrl = (metricId: number,) => {




  return `/api/0.1.0/executions/metrics/${metricId}`
}

/**
 * Retorna uma métrica.
 * @summary Get Metric
 */
export const getMetricApi010ExecutionsMetricsMetricIdGet = async (metricId: number, options?: Parameters<typeof api>[1]): Promise<getMetricApi010ExecutionsMetricsMetricIdGetResponse> => {

  return api<getMetricApi010ExecutionsMetricsMetricIdGetResponse>(getGetMetricApi010ExecutionsMetricsMetricIdGetUrl(metricId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMetricApi010ExecutionsMetricsMetricIdGetQueryKey = (metricId: number,) => {
    return [
    `/api/0.1.0/executions/metrics/${metricId}`
    ] as const;
    }


export const getGetMetricApi010ExecutionsMetricsMetricIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>, TError = HTTPValidationError>(metricId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMetricApi010ExecutionsMetricsMetricIdGetQueryKey(metricId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>> = ({ signal }) => getMetricApi010ExecutionsMetricsMetricIdGet(metricId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: metricId !== null && metricId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMetricApi010ExecutionsMetricsMetricIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>>
export type GetMetricApi010ExecutionsMetricsMetricIdGetQueryError = HTTPValidationError


export function useGetMetricApi010ExecutionsMetricsMetricIdGet<TData = Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>, TError = HTTPValidationError>(
 metricId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>,
          TError,
          Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMetricApi010ExecutionsMetricsMetricIdGet<TData = Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>, TError = HTTPValidationError>(
 metricId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>,
          TError,
          Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMetricApi010ExecutionsMetricsMetricIdGet<TData = Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>, TError = HTTPValidationError>(
 metricId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Metric
 */

export function useGetMetricApi010ExecutionsMetricsMetricIdGet<TData = Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>, TError = HTTPValidationError>(
 metricId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetricApi010ExecutionsMetricsMetricIdGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMetricApi010ExecutionsMetricsMetricIdGetQueryOptions(metricId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetResponse200 = {
  data: AutomationsHubDtoStepsStepResponse[]
  status: 200
}

export type listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetResponseSuccess = (listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetResponse200) & {
  headers: Headers;
};
export type listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetResponseError = (listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetResponse422) & {
  headers: Headers;
};

export type listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetResponse = (listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetResponseSuccess | listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetResponseError)

export const getListExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetUrl = (executionId: number,) => {




  return `/api/0.1.0/executions/executions/${executionId}/steps`
}

/**
 * Lista os steps de uma execução.
 * @summary List Execution Steps
 */
export const listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet = async (executionId: number, options?: Parameters<typeof api>[1]): Promise<listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetResponse> => {

  return api<listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetResponse>(getListExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetUrl(executionId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetQueryKey = (executionId: number,) => {
    return [
    `/api/0.1.0/executions/executions/${executionId}/steps`
    ] as const;
    }


export const getListExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetQueryOptions = <TData = Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>, TError = HTTPValidationError>(executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetQueryKey(executionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>> = ({ signal }) => listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet(executionId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: executionId !== null && executionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>>
export type ListExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetQueryError = HTTPValidationError


export function useListExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet<TData = Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>, TError = HTTPValidationError>(
 executionId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>,
          TError,
          Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet<TData = Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>,
          TError,
          Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet<TData = Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Execution Steps
 */

export function useListExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet<TData = Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListExecutionStepsApi010ExecutionsExecutionsExecutionIdStepsGetQueryOptions(executionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type rootGetResponse200 = {
  data: RootGet200
  status: 200
}

export type rootGetResponseSuccess = (rootGetResponse200) & {
  headers: Headers;
};
;

export type rootGetResponse = (rootGetResponseSuccess)

export const getRootGetUrl = () => {




  return `/`
}

/**
 * @summary Root
 */
export const rootGet = async ( options?: Parameters<typeof api>[1]): Promise<rootGetResponse> => {

  return api<rootGetResponse>(getRootGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getRootGetQueryKey = () => {
    return [
    `/`
    ] as const;
    }


export const getRootGetQueryOptions = <TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRootGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rootGet>>> = ({ signal }) => rootGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RootGetQueryResult = NonNullable<Awaited<ReturnType<typeof rootGet>>>
export type RootGetQueryError = unknown


export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootGet>>,
          TError,
          Awaited<ReturnType<typeof rootGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootGet>>,
          TError,
          Awaited<ReturnType<typeof rootGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Root
 */

export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRootGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type healthHealthGetResponse200 = {
  data: HealthHealthGet200
  status: 200
}

export type healthHealthGetResponseSuccess = (healthHealthGetResponse200) & {
  headers: Headers;
};
;

export type healthHealthGetResponse = (healthHealthGetResponseSuccess)

export const getHealthHealthGetUrl = () => {




  return `/health`
}

/**
 * @summary Health
 */
export const healthHealthGet = async ( options?: Parameters<typeof api>[1]): Promise<healthHealthGetResponse> => {

  return api<healthHealthGetResponse>(getHealthHealthGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthHealthGetQueryKey = () => {
    return [
    `/health`
    ] as const;
    }


export const getHealthHealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthHealthGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthHealthGet>>> = ({ signal }) => healthHealthGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthHealthGet>>>
export type HealthHealthGetQueryError = unknown


export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health
 */

export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthHealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type testErrorTestErrorGetResponse200 = {
  data: unknown
  status: 200
}

export type testErrorTestErrorGetResponseSuccess = (testErrorTestErrorGetResponse200) & {
  headers: Headers;
};
;

export type testErrorTestErrorGetResponse = (testErrorTestErrorGetResponseSuccess)

export const getTestErrorTestErrorGetUrl = () => {




  return `/test-error`
}

/**
 * @summary Test Error
 */
export const testErrorTestErrorGet = async ( options?: Parameters<typeof api>[1]): Promise<testErrorTestErrorGetResponse> => {

  return api<testErrorTestErrorGetResponse>(getTestErrorTestErrorGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getTestErrorTestErrorGetQueryKey = () => {
    return [
    `/test-error`
    ] as const;
    }


export const getTestErrorTestErrorGetQueryOptions = <TData = Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTestErrorTestErrorGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof testErrorTestErrorGet>>> = ({ signal }) => testErrorTestErrorGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TestErrorTestErrorGetQueryResult = NonNullable<Awaited<ReturnType<typeof testErrorTestErrorGet>>>
export type TestErrorTestErrorGetQueryError = unknown


export function useTestErrorTestErrorGet<TData = Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof testErrorTestErrorGet>>,
          TError,
          Awaited<ReturnType<typeof testErrorTestErrorGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTestErrorTestErrorGet<TData = Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof testErrorTestErrorGet>>,
          TError,
          Awaited<ReturnType<typeof testErrorTestErrorGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTestErrorTestErrorGet<TData = Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Test Error
 */

export function useTestErrorTestErrorGet<TData = Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTestErrorTestErrorGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
