/**
 * Generated by orval 🍺
 * Do not edit manually.
 * automations-hub
 *
 *     O `orchestrator-api` é o **control plane** do `organize-tasks`: o serviço que sabe
 *     quais automações existem, qual o status de cada uma, o histórico de execuções,
 *     e consegue pausar/reativar cada uma — sem precisar entrar em cada automação
 *     individualmente pra saber o que está acontecendo.
 *
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { api } from './axios';
export interface AutomationResponse {
  id: number;
  slug: string;
  name: string;
  trigger: string;
  status: string;
}

export interface AutomationStatsResponse {
  success_rate: number;
  average_duration: number;
  total_executions: number;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface MetricResponse {
  id: number;
  execution_at: string;
  name: string;
  value: number;
  step_id: number;
}

export interface PauseAutomationResponse {
  message: string;
}

export interface TriggerAutomationResponse {
  message: string;
}

export interface AutomationsHubDtoAutomationDtoExecutionResponse {
  id: number;
  status: string;
  start_at: string;
  end_at: string | null;
  error_message: string | null;
}

export interface AutomationsHubDtoExecutionDtoStepResponse {
  id: number;
  name: string;
  status: string;
  error_message: string | null;
}

export interface AutomationsHubDtoExecutionDtoExecutionResponse {
  id: number;
  automation_id: number;
  status: string;
  start_at: string;
  end_at: string | null;
  error_message: string | null;
  steps: AutomationsHubDtoExecutionDtoStepResponse[];
}

export interface AutomationsHubDtoStepsStepResponse {
  id: number;
  execution_id: number;
  name: string;
  status: string;
  error_message?: string | null;
}

export type RootGet200 = { [key: string]: unknown };

export type HealthHealthGet200 = { [key: string]: unknown };

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listAutomationsResponse200 = {
  data: AutomationResponse[]
  status: 200
}

export type listAutomationsResponseSuccess = (listAutomationsResponse200) & {
  headers: Headers;
};
;

export type listAutomationsResponse = (listAutomationsResponseSuccess)

export const getListAutomationsUrl = () => {




  return `/api/0.1.0/automations/`
}

/**
 * Lista todas as automações.
 * @summary List Automations
 */
export const listAutomations = async ( options?: Parameters<typeof api>[1]): Promise<listAutomationsResponse> => {

  return api<listAutomationsResponse>(getListAutomationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAutomationsQueryKey = () => {
    return [
    `/api/0.1.0/automations/`
    ] as const;
    }


export const getListAutomationsQueryOptions = <TData = Awaited<ReturnType<typeof listAutomations>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomations>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAutomationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAutomations>>> = ({ signal }) => listAutomations({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAutomations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAutomationsQueryResult = NonNullable<Awaited<ReturnType<typeof listAutomations>>>
export type ListAutomationsQueryError = unknown


export function useListAutomations<TData = Awaited<ReturnType<typeof listAutomations>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAutomations>>,
          TError,
          Awaited<ReturnType<typeof listAutomations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAutomations<TData = Awaited<ReturnType<typeof listAutomations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAutomations>>,
          TError,
          Awaited<ReturnType<typeof listAutomations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAutomations<TData = Awaited<ReturnType<typeof listAutomations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomations>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Automations
 */

export function useListAutomations<TData = Awaited<ReturnType<typeof listAutomations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomations>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAutomationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getAutomationDetailResponse200 = {
  data: AutomationResponse
  status: 200
}

export type getAutomationDetailResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getAutomationDetailResponseSuccess = (getAutomationDetailResponse200) & {
  headers: Headers;
};
export type getAutomationDetailResponseError = (getAutomationDetailResponse422) & {
  headers: Headers;
};

export type getAutomationDetailResponse = (getAutomationDetailResponseSuccess | getAutomationDetailResponseError)

export const getGetAutomationDetailUrl = (slug: string,) => {




  return `/api/0.1.0/automations/${slug}`
}

/**
 * Detalhe de uma automação pelo slug.
 * @summary Get Automation Detail
 */
export const getAutomationDetail = async (slug: string, options?: Parameters<typeof api>[1]): Promise<getAutomationDetailResponse> => {

  return api<getAutomationDetailResponse>(getGetAutomationDetailUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAutomationDetailQueryKey = (slug: string,) => {
    return [
    `/api/0.1.0/automations/${slug}`
    ] as const;
    }


export const getGetAutomationDetailQueryOptions = <TData = Awaited<ReturnType<typeof getAutomationDetail>>, TError = HTTPValidationError>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationDetail>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAutomationDetailQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAutomationDetail>>> = ({ signal }) => getAutomationDetail(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAutomationDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAutomationDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getAutomationDetail>>>
export type GetAutomationDetailQueryError = HTTPValidationError


export function useGetAutomationDetail<TData = Awaited<ReturnType<typeof getAutomationDetail>>, TError = HTTPValidationError>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAutomationDetail>>,
          TError,
          Awaited<ReturnType<typeof getAutomationDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAutomationDetail<TData = Awaited<ReturnType<typeof getAutomationDetail>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAutomationDetail>>,
          TError,
          Awaited<ReturnType<typeof getAutomationDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAutomationDetail<TData = Awaited<ReturnType<typeof getAutomationDetail>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationDetail>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Automation Detail
 */

export function useGetAutomationDetail<TData = Awaited<ReturnType<typeof getAutomationDetail>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationDetail>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAutomationDetailQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type pauseAutomationResponse200 = {
  data: PauseAutomationResponse
  status: 200
}

export type pauseAutomationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type pauseAutomationResponseSuccess = (pauseAutomationResponse200) & {
  headers: Headers;
};
export type pauseAutomationResponseError = (pauseAutomationResponse422) & {
  headers: Headers;
};

export type pauseAutomationResponse = (pauseAutomationResponseSuccess | pauseAutomationResponseError)

export const getPauseAutomationUrl = (slug: string,) => {




  return `/api/0.1.0/automations/${slug}/pause`
}

/**
 * Pausa uma automação.
 * @summary Pause Automation
 */
export const pauseAutomation = async (slug: string, options?: Parameters<typeof api>[1]): Promise<pauseAutomationResponse> => {

  return api<pauseAutomationResponse>(getPauseAutomationUrl(slug),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getPauseAutomationMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pauseAutomation>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof pauseAutomation>>, TError,{slug: string}, TContext> => {

const mutationKey = ['pauseAutomation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pauseAutomation>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  pauseAutomation(slug,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PauseAutomationMutationResult = NonNullable<Awaited<ReturnType<typeof pauseAutomation>>>

    export type PauseAutomationMutationError = HTTPValidationError

    /**
 * @summary Pause Automation
 */
export const usePauseAutomation = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pauseAutomation>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pauseAutomation>>,
        TError,
        {slug: string},
        TContext
      > => {
      return useMutation(getPauseAutomationMutationOptions(options), queryClient);
    }

export type resumeAutomationResponse200 = {
  data: PauseAutomationResponse
  status: 200
}

export type resumeAutomationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type resumeAutomationResponseSuccess = (resumeAutomationResponse200) & {
  headers: Headers;
};
export type resumeAutomationResponseError = (resumeAutomationResponse422) & {
  headers: Headers;
};

export type resumeAutomationResponse = (resumeAutomationResponseSuccess | resumeAutomationResponseError)

export const getResumeAutomationUrl = (slug: string,) => {




  return `/api/0.1.0/automations/${slug}/resume`
}

/**
 * Retoma uma automação.
 * @summary Resume Automation
 */
export const resumeAutomation = async (slug: string, options?: Parameters<typeof api>[1]): Promise<resumeAutomationResponse> => {

  return api<resumeAutomationResponse>(getResumeAutomationUrl(slug),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getResumeAutomationMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resumeAutomation>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof resumeAutomation>>, TError,{slug: string}, TContext> => {

const mutationKey = ['resumeAutomation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resumeAutomation>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  resumeAutomation(slug,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResumeAutomationMutationResult = NonNullable<Awaited<ReturnType<typeof resumeAutomation>>>

    export type ResumeAutomationMutationError = HTTPValidationError

    /**
 * @summary Resume Automation
 */
export const useResumeAutomation = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resumeAutomation>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resumeAutomation>>,
        TError,
        {slug: string},
        TContext
      > => {
      return useMutation(getResumeAutomationMutationOptions(options), queryClient);
    }

export type triggerAutomationResponse200 = {
  data: TriggerAutomationResponse
  status: 200
}

export type triggerAutomationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type triggerAutomationResponseSuccess = (triggerAutomationResponse200) & {
  headers: Headers;
};
export type triggerAutomationResponseError = (triggerAutomationResponse422) & {
  headers: Headers;
};

export type triggerAutomationResponse = (triggerAutomationResponseSuccess | triggerAutomationResponseError)

export const getTriggerAutomationUrl = (slug: string,) => {




  return `/api/0.1.0/automations/${slug}/trigger`
}

/**
 * Dispara execução manual de uma automação.
 * @summary Trigger Automation
 */
export const triggerAutomation = async (slug: string, options?: Parameters<typeof api>[1]): Promise<triggerAutomationResponse> => {

  return api<triggerAutomationResponse>(getTriggerAutomationUrl(slug),
  {
    ...options,
    method: 'POST'


  }
);}





export const getTriggerAutomationMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerAutomation>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof api>}
): UseMutationOptions<Awaited<ReturnType<typeof triggerAutomation>>, TError,{slug: string}, TContext> => {

const mutationKey = ['triggerAutomation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerAutomation>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  triggerAutomation(slug,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TriggerAutomationMutationResult = NonNullable<Awaited<ReturnType<typeof triggerAutomation>>>

    export type TriggerAutomationMutationError = HTTPValidationError

    /**
 * @summary Trigger Automation
 */
export const useTriggerAutomation = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerAutomation>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof triggerAutomation>>,
        TError,
        {slug: string},
        TContext
      > => {
      return useMutation(getTriggerAutomationMutationOptions(options), queryClient);
    }

export type listAutomationExecutionsResponse200 = {
  data: AutomationsHubDtoAutomationDtoExecutionResponse[]
  status: 200
}

export type listAutomationExecutionsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listAutomationExecutionsResponseSuccess = (listAutomationExecutionsResponse200) & {
  headers: Headers;
};
export type listAutomationExecutionsResponseError = (listAutomationExecutionsResponse422) & {
  headers: Headers;
};

export type listAutomationExecutionsResponse = (listAutomationExecutionsResponseSuccess | listAutomationExecutionsResponseError)

export const getListAutomationExecutionsUrl = (slug: string,) => {




  return `/api/0.1.0/automations/${slug}/executions`
}

/**
 * Histórico de execuções dessa automação.
 * @summary List Automation Executions
 */
export const listAutomationExecutions = async (slug: string, options?: Parameters<typeof api>[1]): Promise<listAutomationExecutionsResponse> => {

  return api<listAutomationExecutionsResponse>(getListAutomationExecutionsUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAutomationExecutionsQueryKey = (slug: string,) => {
    return [
    `/api/0.1.0/automations/${slug}/executions`
    ] as const;
    }


export const getListAutomationExecutionsQueryOptions = <TData = Awaited<ReturnType<typeof listAutomationExecutions>>, TError = HTTPValidationError>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomationExecutions>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAutomationExecutionsQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAutomationExecutions>>> = ({ signal }) => listAutomationExecutions(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAutomationExecutions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAutomationExecutionsQueryResult = NonNullable<Awaited<ReturnType<typeof listAutomationExecutions>>>
export type ListAutomationExecutionsQueryError = HTTPValidationError


export function useListAutomationExecutions<TData = Awaited<ReturnType<typeof listAutomationExecutions>>, TError = HTTPValidationError>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomationExecutions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAutomationExecutions>>,
          TError,
          Awaited<ReturnType<typeof listAutomationExecutions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAutomationExecutions<TData = Awaited<ReturnType<typeof listAutomationExecutions>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomationExecutions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAutomationExecutions>>,
          TError,
          Awaited<ReturnType<typeof listAutomationExecutions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAutomationExecutions<TData = Awaited<ReturnType<typeof listAutomationExecutions>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomationExecutions>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Automation Executions
 */

export function useListAutomationExecutions<TData = Awaited<ReturnType<typeof listAutomationExecutions>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutomationExecutions>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAutomationExecutionsQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getAutomationStatsResponse200 = {
  data: AutomationStatsResponse
  status: 200
}

export type getAutomationStatsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getAutomationStatsResponseSuccess = (getAutomationStatsResponse200) & {
  headers: Headers;
};
export type getAutomationStatsResponseError = (getAutomationStatsResponse422) & {
  headers: Headers;
};

export type getAutomationStatsResponse = (getAutomationStatsResponseSuccess | getAutomationStatsResponseError)

export const getGetAutomationStatsUrl = (slug: string,) => {




  return `/api/0.1.0/automations/${slug}/stats`
}

/**
 * Taxa de sucesso e duração média da automação.
 * @summary Get Automation Stats
 */
export const getAutomationStats = async (slug: string, options?: Parameters<typeof api>[1]): Promise<getAutomationStatsResponse> => {

  return api<getAutomationStatsResponse>(getGetAutomationStatsUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAutomationStatsQueryKey = (slug: string,) => {
    return [
    `/api/0.1.0/automations/${slug}/stats`
    ] as const;
    }


export const getGetAutomationStatsQueryOptions = <TData = Awaited<ReturnType<typeof getAutomationStats>>, TError = HTTPValidationError>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationStats>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAutomationStatsQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAutomationStats>>> = ({ signal }) => getAutomationStats(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAutomationStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAutomationStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getAutomationStats>>>
export type GetAutomationStatsQueryError = HTTPValidationError


export function useGetAutomationStats<TData = Awaited<ReturnType<typeof getAutomationStats>>, TError = HTTPValidationError>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAutomationStats>>,
          TError,
          Awaited<ReturnType<typeof getAutomationStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAutomationStats<TData = Awaited<ReturnType<typeof getAutomationStats>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAutomationStats>>,
          TError,
          Awaited<ReturnType<typeof getAutomationStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAutomationStats<TData = Awaited<ReturnType<typeof getAutomationStats>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationStats>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Automation Stats
 */

export function useGetAutomationStats<TData = Awaited<ReturnType<typeof getAutomationStats>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationStats>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAutomationStatsQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getExecutionDetailResponse200 = {
  data: AutomationsHubDtoExecutionDtoExecutionResponse
  status: 200
}

export type getExecutionDetailResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getExecutionDetailResponseSuccess = (getExecutionDetailResponse200) & {
  headers: Headers;
};
export type getExecutionDetailResponseError = (getExecutionDetailResponse422) & {
  headers: Headers;
};

export type getExecutionDetailResponse = (getExecutionDetailResponseSuccess | getExecutionDetailResponseError)

export const getGetExecutionDetailUrl = (executionId: number,) => {




  return `/api/0.1.0/executions/${executionId}`
}

/**
 * Detalhe de uma execução (com steps).
 * @summary Get Execution Detail
 */
export const getExecutionDetail = async (executionId: number, options?: Parameters<typeof api>[1]): Promise<getExecutionDetailResponse> => {

  return api<getExecutionDetailResponse>(getGetExecutionDetailUrl(executionId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetExecutionDetailQueryKey = (executionId: number,) => {
    return [
    `/api/0.1.0/executions/${executionId}`
    ] as const;
    }


export const getGetExecutionDetailQueryOptions = <TData = Awaited<ReturnType<typeof getExecutionDetail>>, TError = HTTPValidationError>(executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionDetail>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetExecutionDetailQueryKey(executionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getExecutionDetail>>> = ({ signal }) => getExecutionDetail(executionId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: executionId !== null && executionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getExecutionDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetExecutionDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getExecutionDetail>>>
export type GetExecutionDetailQueryError = HTTPValidationError


export function useGetExecutionDetail<TData = Awaited<ReturnType<typeof getExecutionDetail>>, TError = HTTPValidationError>(
 executionId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecutionDetail>>,
          TError,
          Awaited<ReturnType<typeof getExecutionDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExecutionDetail<TData = Awaited<ReturnType<typeof getExecutionDetail>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecutionDetail>>,
          TError,
          Awaited<ReturnType<typeof getExecutionDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExecutionDetail<TData = Awaited<ReturnType<typeof getExecutionDetail>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionDetail>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Execution Detail
 */

export function useGetExecutionDetail<TData = Awaited<ReturnType<typeof getExecutionDetail>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionDetail>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetExecutionDetailQueryOptions(executionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getExecutionStepsResponse200 = {
  data: AutomationsHubDtoExecutionDtoStepResponse[]
  status: 200
}

export type getExecutionStepsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getExecutionStepsResponseSuccess = (getExecutionStepsResponse200) & {
  headers: Headers;
};
export type getExecutionStepsResponseError = (getExecutionStepsResponse422) & {
  headers: Headers;
};

export type getExecutionStepsResponse = (getExecutionStepsResponseSuccess | getExecutionStepsResponseError)

export const getGetExecutionStepsUrl = (executionId: number,) => {




  return `/api/0.1.0/executions/${executionId}/steps`
}

/**
 * Só os steps dessa execução.
 * @summary Get Execution Steps
 */
export const getExecutionSteps = async (executionId: number, options?: Parameters<typeof api>[1]): Promise<getExecutionStepsResponse> => {

  return api<getExecutionStepsResponse>(getGetExecutionStepsUrl(executionId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetExecutionStepsQueryKey = (executionId: number,) => {
    return [
    `/api/0.1.0/executions/${executionId}/steps`
    ] as const;
    }


export const getGetExecutionStepsQueryOptions = <TData = Awaited<ReturnType<typeof getExecutionSteps>>, TError = HTTPValidationError>(executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionSteps>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetExecutionStepsQueryKey(executionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getExecutionSteps>>> = ({ signal }) => getExecutionSteps(executionId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: executionId !== null && executionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getExecutionSteps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetExecutionStepsQueryResult = NonNullable<Awaited<ReturnType<typeof getExecutionSteps>>>
export type GetExecutionStepsQueryError = HTTPValidationError


export function useGetExecutionSteps<TData = Awaited<ReturnType<typeof getExecutionSteps>>, TError = HTTPValidationError>(
 executionId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionSteps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecutionSteps>>,
          TError,
          Awaited<ReturnType<typeof getExecutionSteps>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExecutionSteps<TData = Awaited<ReturnType<typeof getExecutionSteps>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionSteps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecutionSteps>>,
          TError,
          Awaited<ReturnType<typeof getExecutionSteps>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExecutionSteps<TData = Awaited<ReturnType<typeof getExecutionSteps>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionSteps>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Execution Steps
 */

export function useGetExecutionSteps<TData = Awaited<ReturnType<typeof getExecutionSteps>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExecutionSteps>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetExecutionStepsQueryOptions(executionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type listStepMetricsResponse200 = {
  data: MetricResponse[]
  status: 200
}

export type listStepMetricsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listStepMetricsResponseSuccess = (listStepMetricsResponse200) & {
  headers: Headers;
};
export type listStepMetricsResponseError = (listStepMetricsResponse422) & {
  headers: Headers;
};

export type listStepMetricsResponse = (listStepMetricsResponseSuccess | listStepMetricsResponseError)

export const getListStepMetricsUrl = (stepId: number,) => {




  return `/api/0.1.0/executions/steps/${stepId}/metrics`
}

/**
 * Lista as métricas de um step.
 * @summary List Step Metrics
 */
export const listStepMetrics = async (stepId: number, options?: Parameters<typeof api>[1]): Promise<listStepMetricsResponse> => {

  return api<listStepMetricsResponse>(getListStepMetricsUrl(stepId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListStepMetricsQueryKey = (stepId: number,) => {
    return [
    `/api/0.1.0/executions/steps/${stepId}/metrics`
    ] as const;
    }


export const getListStepMetricsQueryOptions = <TData = Awaited<ReturnType<typeof listStepMetrics>>, TError = HTTPValidationError>(stepId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStepMetrics>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStepMetricsQueryKey(stepId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStepMetrics>>> = ({ signal }) => listStepMetrics(stepId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: stepId !== null && stepId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStepMetrics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStepMetricsQueryResult = NonNullable<Awaited<ReturnType<typeof listStepMetrics>>>
export type ListStepMetricsQueryError = HTTPValidationError


export function useListStepMetrics<TData = Awaited<ReturnType<typeof listStepMetrics>>, TError = HTTPValidationError>(
 stepId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStepMetrics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStepMetrics>>,
          TError,
          Awaited<ReturnType<typeof listStepMetrics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStepMetrics<TData = Awaited<ReturnType<typeof listStepMetrics>>, TError = HTTPValidationError>(
 stepId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStepMetrics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStepMetrics>>,
          TError,
          Awaited<ReturnType<typeof listStepMetrics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStepMetrics<TData = Awaited<ReturnType<typeof listStepMetrics>>, TError = HTTPValidationError>(
 stepId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStepMetrics>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Step Metrics
 */

export function useListStepMetrics<TData = Awaited<ReturnType<typeof listStepMetrics>>, TError = HTTPValidationError>(
 stepId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStepMetrics>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStepMetricsQueryOptions(stepId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getMetricResponse200 = {
  data: MetricResponse
  status: 200
}

export type getMetricResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getMetricResponseSuccess = (getMetricResponse200) & {
  headers: Headers;
};
export type getMetricResponseError = (getMetricResponse422) & {
  headers: Headers;
};

export type getMetricResponse = (getMetricResponseSuccess | getMetricResponseError)

export const getGetMetricUrl = (metricId: number,) => {




  return `/api/0.1.0/executions/metrics/${metricId}`
}

/**
 * Retorna uma métrica.
 * @summary Get Metric
 */
export const getMetric = async (metricId: number, options?: Parameters<typeof api>[1]): Promise<getMetricResponse> => {

  return api<getMetricResponse>(getGetMetricUrl(metricId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMetricQueryKey = (metricId: number,) => {
    return [
    `/api/0.1.0/executions/metrics/${metricId}`
    ] as const;
    }


export const getGetMetricQueryOptions = <TData = Awaited<ReturnType<typeof getMetric>>, TError = HTTPValidationError>(metricId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetric>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMetricQueryKey(metricId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMetric>>> = ({ signal }) => getMetric(metricId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: metricId !== null && metricId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMetric>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMetricQueryResult = NonNullable<Awaited<ReturnType<typeof getMetric>>>
export type GetMetricQueryError = HTTPValidationError


export function useGetMetric<TData = Awaited<ReturnType<typeof getMetric>>, TError = HTTPValidationError>(
 metricId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetric>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetric>>,
          TError,
          Awaited<ReturnType<typeof getMetric>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMetric<TData = Awaited<ReturnType<typeof getMetric>>, TError = HTTPValidationError>(
 metricId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetric>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetric>>,
          TError,
          Awaited<ReturnType<typeof getMetric>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMetric<TData = Awaited<ReturnType<typeof getMetric>>, TError = HTTPValidationError>(
 metricId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetric>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Metric
 */

export function useGetMetric<TData = Awaited<ReturnType<typeof getMetric>>, TError = HTTPValidationError>(
 metricId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetric>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMetricQueryOptions(metricId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type listExecutionStepsResponse200 = {
  data: AutomationsHubDtoStepsStepResponse[]
  status: 200
}

export type listExecutionStepsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listExecutionStepsResponseSuccess = (listExecutionStepsResponse200) & {
  headers: Headers;
};
export type listExecutionStepsResponseError = (listExecutionStepsResponse422) & {
  headers: Headers;
};

export type listExecutionStepsResponse = (listExecutionStepsResponseSuccess | listExecutionStepsResponseError)

export const getListExecutionStepsUrl = (executionId: number,) => {




  return `/api/0.1.0/executions/executions/${executionId}/steps`
}

/**
 * Lista os steps de uma execução.
 * @summary List Execution Steps
 */
export const listExecutionSteps = async (executionId: number, options?: Parameters<typeof api>[1]): Promise<listExecutionStepsResponse> => {

  return api<listExecutionStepsResponse>(getListExecutionStepsUrl(executionId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListExecutionStepsQueryKey = (executionId: number,) => {
    return [
    `/api/0.1.0/executions/executions/${executionId}/steps`
    ] as const;
    }


export const getListExecutionStepsQueryOptions = <TData = Awaited<ReturnType<typeof listExecutionSteps>>, TError = HTTPValidationError>(executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExecutionSteps>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListExecutionStepsQueryKey(executionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listExecutionSteps>>> = ({ signal }) => listExecutionSteps(executionId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: executionId !== null && executionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listExecutionSteps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListExecutionStepsQueryResult = NonNullable<Awaited<ReturnType<typeof listExecutionSteps>>>
export type ListExecutionStepsQueryError = HTTPValidationError


export function useListExecutionSteps<TData = Awaited<ReturnType<typeof listExecutionSteps>>, TError = HTTPValidationError>(
 executionId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExecutionSteps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExecutionSteps>>,
          TError,
          Awaited<ReturnType<typeof listExecutionSteps>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListExecutionSteps<TData = Awaited<ReturnType<typeof listExecutionSteps>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExecutionSteps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExecutionSteps>>,
          TError,
          Awaited<ReturnType<typeof listExecutionSteps>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListExecutionSteps<TData = Awaited<ReturnType<typeof listExecutionSteps>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExecutionSteps>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Execution Steps
 */

export function useListExecutionSteps<TData = Awaited<ReturnType<typeof listExecutionSteps>>, TError = HTTPValidationError>(
 executionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExecutionSteps>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListExecutionStepsQueryOptions(executionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type rootGetResponse200 = {
  data: RootGet200
  status: 200
}

export type rootGetResponseSuccess = (rootGetResponse200) & {
  headers: Headers;
};
;

export type rootGetResponse = (rootGetResponseSuccess)

export const getRootGetUrl = () => {




  return `/`
}

/**
 * @summary Root
 */
export const rootGet = async ( options?: Parameters<typeof api>[1]): Promise<rootGetResponse> => {

  return api<rootGetResponse>(getRootGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getRootGetQueryKey = () => {
    return [
    `/`
    ] as const;
    }


export const getRootGetQueryOptions = <TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRootGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rootGet>>> = ({ signal }) => rootGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RootGetQueryResult = NonNullable<Awaited<ReturnType<typeof rootGet>>>
export type RootGetQueryError = unknown


export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootGet>>,
          TError,
          Awaited<ReturnType<typeof rootGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootGet>>,
          TError,
          Awaited<ReturnType<typeof rootGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Root
 */

export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRootGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type healthHealthGetResponse200 = {
  data: HealthHealthGet200
  status: 200
}

export type healthHealthGetResponseSuccess = (healthHealthGetResponse200) & {
  headers: Headers;
};
;

export type healthHealthGetResponse = (healthHealthGetResponseSuccess)

export const getHealthHealthGetUrl = () => {




  return `/health`
}

/**
 * @summary Health
 */
export const healthHealthGet = async ( options?: Parameters<typeof api>[1]): Promise<healthHealthGetResponse> => {

  return api<healthHealthGetResponse>(getHealthHealthGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthHealthGetQueryKey = () => {
    return [
    `/health`
    ] as const;
    }


export const getHealthHealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthHealthGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthHealthGet>>> = ({ signal }) => healthHealthGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthHealthGet>>>
export type HealthHealthGetQueryError = unknown


export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health
 */

export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthHealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type testErrorTestErrorGetResponse200 = {
  data: unknown
  status: 200
}

export type testErrorTestErrorGetResponseSuccess = (testErrorTestErrorGetResponse200) & {
  headers: Headers;
};
;

export type testErrorTestErrorGetResponse = (testErrorTestErrorGetResponseSuccess)

export const getTestErrorTestErrorGetUrl = () => {




  return `/test-error`
}

/**
 * @summary Test Error
 */
export const testErrorTestErrorGet = async ( options?: Parameters<typeof api>[1]): Promise<testErrorTestErrorGetResponse> => {

  return api<testErrorTestErrorGetResponse>(getTestErrorTestErrorGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getTestErrorTestErrorGetQueryKey = () => {
    return [
    `/test-error`
    ] as const;
    }


export const getTestErrorTestErrorGetQueryOptions = <TData = Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTestErrorTestErrorGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof testErrorTestErrorGet>>> = ({ signal }) => testErrorTestErrorGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TestErrorTestErrorGetQueryResult = NonNullable<Awaited<ReturnType<typeof testErrorTestErrorGet>>>
export type TestErrorTestErrorGetQueryError = unknown


export function useTestErrorTestErrorGet<TData = Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof testErrorTestErrorGet>>,
          TError,
          Awaited<ReturnType<typeof testErrorTestErrorGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTestErrorTestErrorGet<TData = Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof testErrorTestErrorGet>>,
          TError,
          Awaited<ReturnType<typeof testErrorTestErrorGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTestErrorTestErrorGet<TData = Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Test Error
 */

export function useTestErrorTestErrorGet<TData = Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testErrorTestErrorGet>>, TError, TData>>, request?: SecondParameter<typeof api>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTestErrorTestErrorGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
